using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using asec.Compatibility.CollectiveAccess;
using asec.Models;
using asec.Models.Archive;
using asec.Models.Digitalization;

namespace asec.Controllers;

[ApiController]
[Route("/api/v1/export")]
public class ExportController : ControllerBase
{
    private readonly ILogger<ExportController> _logger;
    private readonly EditClient _editClient;
    private readonly AsecDBContext _dbContext;

    private readonly string _storageBaseUrl;

    public ExportController(EditClient editClient, AsecDBContext dbContext, ILogger<ExportController> logger, IConfiguration configuration) : base()
    {
        _editClient = editClient;
        _logger = logger;
        _dbContext = dbContext;
        
        var storageSection = configuration.GetSection("ObjectStorage");
        _storageBaseUrl = $"{storageSection.GetValue<string>("Endpoint")}/{storageSection.GetValue<string>("ArtefactBucket")}";
    }

    [HttpPost("artefact/{id}")]
    public async Task<IActionResult> ExportArtefact(string id, CancellationToken cancellationToken = default(CancellationToken))
    {
        var guid = Guid.Parse(id);
        var artefact = _dbContext.DigitalObjects
            .Include(d => d.WorkVersions)
            .Include(d => d.PhysicalObject)
            .OfType<Artefact>()
            .FirstOrDefault(a => a.Id == guid);
        if (artefact == null)
        {
            return NotFound();
        }

        PrepareArtefact(artefact);
        var remoteId = await _editClient.AddOrUpdateDigitalObject(artefact, cancellationToken);
        artefact.RemoteId = remoteId;
        artefact.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.Artefact.FromDBEntity(artefact));
    }

    [HttpPost("paratext/{id}")]
    public async Task<IActionResult> ExportParatext(string id, CancellationToken cancellationToken = default(CancellationToken))
    {
        var guid = Guid.Parse(id);
        var paratext = await _dbContext.Paratexts
            .Include(p => p.DigitalObject)
            .FirstOrDefaultAsync(p => p.Id == guid, cancellationToken);
        if (paratext == null)
        {
            return NotFound();
        }
        if (!paratext.CanExport)
        {
            _logger.LogError($"Cannot export paratext {guid}, it was not generated by us!");
            return BadRequest();
        }

        PrepareParatext(paratext);
        var remoteId = await _editClient.AddOrUpdateParatext(paratext, cancellationToken);
        paratext.RemoteId = remoteId;
        paratext.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.Paratext.FromDBEntity(paratext));
    }

    private void PrepareParatext(Paratext paratext)
    {
        
    }

    private void PrepareArtefact(Artefact artefact)
    {
        artefact.InternalNote = "Digitalized version";
        artefact.FedoraUrl = $"{_storageBaseUrl}/{artefact.ObjectId}";
    }
}
