using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Minio;
using Minio.DataModel.Args;
using asec.Compatibility.CollectiveAccess;
using asec.Models;
using asec.Models.Archive;
using asec.Models.Digitalization;
using asec.Models.Emulation;
using asec.Compatibility.EaasApi;

namespace asec.Controllers;

[ApiController]
[Route("/api/v1/export")]
public class ExportController : ControllerBase
{
    private readonly ILogger<ExportController> _logger;
    private readonly EditClient _editClient;
    private readonly AsecDBContext _dbContext;
    private readonly EnvironmentRepositoryClient _eaasEnvRepoClient;

    private readonly IMinioClient _localMinioClient;
    private readonly IMinioClient _archiveMinioClient;

    private readonly string _digitalObjectBucket;
    private readonly string _artefactFolder;
    private readonly string _playableFolder;
    private readonly string _archiveDigitalObjectBucket;
    private readonly string _archiveArtefactFolder;
    private readonly string _archivePlayableFolder;
    private readonly string _localCacheDir;

    public ExportController(
            EditClient editClient,
            AsecDBContext dbContext,
            EnvironmentRepositoryClient eaasEnvRepoClient,
            ILogger<ExportController> logger,
            IConfiguration configuration,
            [FromKeyedServices("LocalObjectStorage")] IMinioClient localMinioClient,
            [FromKeyedServices("ArchiveObjectStorage")] IMinioClient archiveMinioClient) : base()
    {
        _editClient = editClient;
        _logger = logger;
        _dbContext = dbContext;
        _eaasEnvRepoClient = eaasEnvRepoClient;

        _localMinioClient = localMinioClient;
        _archiveMinioClient = archiveMinioClient;

        var storageSection = configuration.GetSection("LocalObjectStorage");
        _digitalObjectBucket = storageSection.GetValue<string>("DigitalObjectBucket");
        _artefactFolder = storageSection.GetValue<string>("ArtefactFolder");
        _playableFolder = storageSection.GetValue<string>("PlayableFolder");

        _localCacheDir = storageSection.GetValue<string>("CacheDir");

        var archiveStorageSection = configuration.GetSection("ArchiveObjectStorage");
        _archiveDigitalObjectBucket = archiveStorageSection.GetValue<string>("DigitalObjectBucket");
        _archiveArtefactFolder = archiveStorageSection.GetValue<string>("ArtefactFolder");
        _archivePlayableFolder = archiveStorageSection.GetValue<string>("PlayableFolder");
    }

    [HttpPost("artefact/{id}")]
    public async Task<IActionResult> ExportArtefact(string id, CancellationToken cancellationToken = default(CancellationToken))
    {
        var guid = Guid.Parse(id);
        var artefact = _dbContext.DigitalObjects
            .Include(d => d.WorkVersions)
            .Include(d => d.PhysicalObject)
            .OfType<Artefact>()
            .FirstOrDefault(a => a.Id == guid);
        if (artefact == null)
        {
            return NotFound();
        }

        await PrepareArtefact(artefact);
        var remoteId = await _editClient.AddOrUpdateDigitalObject(artefact, cancellationToken);
        artefact.RemoteId = remoteId;
        artefact.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.Artefact.FromDBEntity(artefact));
    }

    [HttpPost("paratext/{id}")]
    public async Task<IActionResult> ExportParatext(string id, CancellationToken cancellationToken = default(CancellationToken))
    {
        var guid = Guid.Parse(id);
        var paratext = await _dbContext.Paratexts
            .Include(p => p.DigitalObjects)
            .FirstOrDefaultAsync(p => p.Id == guid, cancellationToken);
        if (paratext == null)
        {
            return NotFound();
        }
        if (!paratext.CanExport)
        {
            _logger.LogError($"Cannot export paratext {guid}, it was not generated by us!");
            return BadRequest();
        }

        PrepareParatext(paratext);
        var remoteId = await _editClient.AddOrUpdateParatext(paratext, cancellationToken);
        paratext.RemoteId = remoteId;
        paratext.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.Paratext.FromDBEntity(paratext));
    }

    [HttpPost("playable/{id}")]
    public async Task<IActionResult> ExportPlayableObject(Guid id, CancellationToken cancellationToken = default)
    {
        var playableObject = _dbContext.DigitalObjects
            .Include(d => d.WorkVersions)
            .Include(d => d.PhysicalObject)
            .OfType<PlayableObject>()
            .FirstOrDefault(a => a.Id == id);
        if (playableObject == null)
        {
            return NotFound();
        }

        await _dbContext.Entry(playableObject).Collection(d => d.IncludedDigitalObjects).LoadAsync(cancellationToken);

        await PreparePlayableObject(playableObject);
        var remoteId = await _editClient.AddOrUpdateDigitalObject(playableObject, cancellationToken);
        playableObject.RemoteId = remoteId;
        playableObject.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.PlayableObject.FromDBEntity(playableObject));
    }

    private void PrepareParatext(Paratext paratext)
    {

    }

    private async Task PreparePlayableObject(PlayableObject playableObject, CancellationToken cancellationToken = default)
    {
        // TODO: this is currently similar to artefact preparation. We might consider merging these.

        Directory.CreateDirectory(_localCacheDir);

        // Push our local image from EaaS object to the remote/archive storage.
        _logger.LogInformation($"Downloading image {playableObject.ObjectId}");
        var tmpFilename = await _eaasEnvRepoClient.DownloadImage(playableObject.ObjectId, _localCacheDir, cancellationToken);

        _logger.LogInformation($"Uploading artefact {playableObject.ObjectId} (cached at '{tmpFilename}') to remote storage.");
        var putArgs = new PutObjectArgs()
            .WithBucket(_archiveDigitalObjectBucket)
            //.WithTagging(artefactTags)
            .WithObject($"{_archivePlayableFolder}/{playableObject.ObjectId}")
            .WithFileName(tmpFilename);
        // TODO: can we stream the data directly instead of creating a temporary file?
        await _archiveMinioClient.PutObjectAsync(putArgs, cancellationToken);
        _logger.LogInformation($"Transfer of artefact {playableObject.FileName} done.");
        playableObject.RepoUrl = playableObject.ObjectId.ToString();
    }


    private async Task PrepareArtefact(Artefact artefact, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_localCacheDir);

        // Push our local minio object to the remote/archive storage.

        var getTagsArgs = new GetObjectTagsArgs()
            .WithBucket(_digitalObjectBucket)
            .WithObject($"{_artefactFolder}/{artefact.ObjectId}");
        var artefactTags = await _localMinioClient.GetObjectTagsAsync(getTagsArgs, cancellationToken);

        var statArgs = new StatObjectArgs()
            .WithBucket(_digitalObjectBucket)
            .WithObject($"{_artefactFolder}/{artefact.ObjectId}");
        var artefactStats = await _localMinioClient.StatObjectAsync(statArgs, cancellationToken);

        var tmpFilename = Path.Combine(_localCacheDir, artefact.FileName);

        _logger.LogInformation($"Downloading artefact {artefact.FileName} with {artefactTags.Tags.Count()} tags of size {artefactStats.Size} bytes from local storage.");
        var getArgs = new GetObjectArgs()
            .WithBucket(_digitalObjectBucket)
            .WithObject($"{_artefactFolder}/{artefact.ObjectId}")
            .WithFile(tmpFilename);
        await _localMinioClient.GetObjectAsync(getArgs, cancellationToken);

        _logger.LogInformation($"{_archiveMinioClient.Config.Secure}");

        _logger.LogInformation($"Uploading artefact {artefact.FileName} (cached at '{tmpFilename}') to remote storage.");
        var putArgs = new PutObjectArgs()
            .WithBucket(_archiveDigitalObjectBucket)
            .WithTagging(artefactTags)
            .WithObject($"{_archiveArtefactFolder}/{artefact.ObjectId}")
            .WithFileName(tmpFilename);
        // TODO: can we stream the data directly instead of creating a temporary file?
        await _archiveMinioClient.PutObjectAsync(putArgs, cancellationToken);
        _logger.LogInformation($"Transfer of artefact {artefact.FileName} done.");
        artefact.RepoUrl = artefact.ObjectId.ToString();
    }
}
