using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Minio;
using Minio.DataModel.Args;
using asec.Compatibility.CollectiveAccess;
using asec.Models;
using asec.Models.Archive;
using asec.Models.Digitalization;

namespace asec.Controllers;

[ApiController]
[Route("/api/v1/export")]
public class ExportController : ControllerBase
{
    private readonly ILogger<ExportController> _logger;
    private readonly EditClient _editClient;
    private readonly AsecDBContext _dbContext;

    private readonly IMinioClient _localMinioClient;
    private readonly IMinioClient _archiveMinioClient;

    private readonly string _artefactBucket;
    private readonly string _archiveArtefactBucket;

    private readonly string _localCacheDir;

    public ExportController(
            EditClient editClient,
            AsecDBContext dbContext,
            ILogger<ExportController> logger,
            IConfiguration configuration,
            [FromKeyedServices("LocalObjectStorage")] IMinioClient localMinioClient,
            [FromKeyedServices("ArchiveObjectStorage")] IMinioClient archiveMinioClient) : base()
    {
        _editClient = editClient;
        _logger = logger;
        _dbContext = dbContext;

        _localMinioClient = localMinioClient;
        _archiveMinioClient = archiveMinioClient;

        var storageSection = configuration.GetSection("LocalObjectStorage");
        _artefactBucket = storageSection.GetValue<string>("ArtefactBucket");
        _localCacheDir = storageSection.GetValue<string>("CacheDir");

        var archiveStorageSection = configuration.GetSection("ArchiveObjectStorage");
        _archiveArtefactBucket = archiveStorageSection.GetValue<string>("ArtefactBucket");
    }

    [HttpPost("artefact/{id}")]
    public async Task<IActionResult> ExportArtefact(string id, CancellationToken cancellationToken = default(CancellationToken))
    {
        var guid = Guid.Parse(id);
        var artefact = _dbContext.DigitalObjects
            .Include(d => d.WorkVersions)
            .Include(d => d.PhysicalObject)
            .OfType<Artefact>()
            .FirstOrDefault(a => a.Id == guid);
        if (artefact == null)
        {
            return NotFound();
        }

        await PrepareArtefact(artefact);
        var remoteId = await _editClient.AddOrUpdateDigitalObject(artefact, cancellationToken);
        artefact.RemoteId = remoteId;
        artefact.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.Artefact.FromDBEntity(artefact));
    }

    [HttpPost("paratext/{id}")]
    public async Task<IActionResult> ExportParatext(string id, CancellationToken cancellationToken = default(CancellationToken))
    {
        var guid = Guid.Parse(id);
        var paratext = await _dbContext.Paratexts
            .Include(p => p.DigitalObjects)
            .FirstOrDefaultAsync(p => p.Id == guid, cancellationToken);
        if (paratext == null)
        {
            return NotFound();
        }
        if (!paratext.CanExport)
        {
            _logger.LogError($"Cannot export paratext {guid}, it was not generated by us!");
            return BadRequest();
        }

        PrepareParatext(paratext);
        var remoteId = await _editClient.AddOrUpdateParatext(paratext, cancellationToken);
        paratext.RemoteId = remoteId;
        paratext.ExportedAt = DateTime.Now;
        await _dbContext.SaveChangesAsync();

        return Ok(ViewModels.Paratext.FromDBEntity(paratext));
    }

    private void PrepareParatext(Paratext paratext)
    {

    }

    private async Task PrepareArtefact(Artefact artefact, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_localCacheDir);
        artefact.InternalNote = "Digitalized version";

        // Push our local minio object to the remote/archive storage.

        var getTagsArgs = new GetObjectTagsArgs()
            .WithBucket(_artefactBucket)
            .WithObject(artefact.ObjectId.ToString());
        var artefactTags = await _localMinioClient.GetObjectTagsAsync(getTagsArgs, cancellationToken);

        var statArgs = new StatObjectArgs()
            .WithBucket(_artefactBucket)
            .WithObject(artefact.ObjectId.ToString());
        var artefactStats = await _localMinioClient.StatObjectAsync(statArgs, cancellationToken);

        var tmpFilename = Path.Combine(_localCacheDir, artefact.FileName);

        _logger.LogInformation($"Downloading artefact {artefact.FileName} with {artefactTags.Tags.Count()} tags of size {artefactStats.Size} bytes from local storage.");
        var getArgs = new GetObjectArgs()
            .WithBucket(_artefactBucket)
            .WithObject(artefact.ObjectId.ToString())
            .WithFile(tmpFilename);
        await _localMinioClient.GetObjectAsync(getArgs, cancellationToken);

        _logger.LogInformation($"{_archiveMinioClient.Config.Secure}");

        _logger.LogInformation($"Uploading artefact {artefact.FileName} (cached at '{tmpFilename}') to remote storage.");
        var putArgs = new PutObjectArgs()
            .WithBucket(_archiveArtefactBucket)
            .WithTagging(artefactTags)
            .WithObject(artefact.ObjectId.ToString())
            .WithFileName(tmpFilename);
        // TODO: can we stream the data directly instead of creating a temporary file?
        await _archiveMinioClient.PutObjectAsync(putArgs, cancellationToken);
        _logger.LogInformation($"Transfer of artefact {artefact.FileName} done.");
        artefact.RepoUrl = artefact.ObjectId.ToString();

    }
}
